site_name: LearnCpp-cn
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.tooltips
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
  extra:
    tags:
      HTML5: html
      JavaScript: js
      CSS: css
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - tags
  - ezlinks:
      wikilinks: true