site_name: LearnCpp 中文版
repo_url: https://github.com/hanxiaomax/Learncpp_CN
repo_name: hanxiaomax/Learncpp_CN
edit_uri: ""
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: teal
    accent: blue
  features:
    - navigation.instant
    - navigation.top
    - content.tooltips
    - header.autohide
    - navigation.indexes
    - navigation.tabs
    - navigation.prune
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
plugins:
  - tags:
      tags_file: tags.md
  - search
  - roamlinks
extra:
  search:
    language: "zh"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hanxiaomax
nav:
  - 总目录: MOC.md
  - 课程内容:
      - 1. C++ 基础:
          - "1-1-Statements-and-the-structure-of-a-program.md"
          - "1-2-comments.md"
          - "1-3-Introduction-to-objects-and-variables.md"
          - "1-4-Variable-assignment-and-initialization.md"
          - "1-5-Introduction-to-iostream-cout-cin-and-endl.md"
          - "1-6-Uninitialized-variables-and-undefined-behavior.md"
          - "1-7-Keywords-and-naming-identifiers.md"
          - "1-8-Whitespace-and-basic-formatting.md"
          - "1-9-Introduction-to-literals-and-operators.md"
          - "1-10-Introduction-to-expressions.md"
          - "1-11-Developing-your-first-program.md"
          - "1-x-Chapter-1-summary-and-quiz.md"
      - 2. C++ 基础-函数和文件:
          - "2-1-Introduction-to-functions.md"
          - "2-2-Function-return-values-value-returning functions.md"
          - "2-3-Void-functions-non-value returning functions.md"
          - "2-4-Introduction-to-function-parameters-and-arguments.md"
          - "2-5-Introduction-to-local-scope.md"
          - "2-6-Why-functions-are-useful-and-how-to-use-them-effectively.md"
          - "2-7-Forward-declarations-and-definitions.md"
          - "2-8-Programs-with-multiple-code-files.md"
          - "2-9-Naming-collisions-and-an-introduction-to-namespaces.md"
          - "2-10-Introduction-to-the-preprocessor.md"
          - "2-11-Header-files.md"
          - "2-12-Header-guards.md"
          - "2-13-How-to-design-your-first-programs.md"
          - "2-x-Chapter-2-summary-and-quiz.md"
      - 3. 调试 C++ 程序:
          - "3-1-Syntax-and-semantic-errors.md"
          - "3-2-The-debugging-process.md"
          - "3-3-A-strategy-for-debugging.md"
          - "3-4-Basic-debugging-tactics.md"
          - "3-5-More-debugging-tactics.md"
          - "3-6-Using-an-integrated-debugger-Stepping.md"
          - "3-7-Using-an-integrated-debugger-Running-and-breakpoints.md"
          - "3-8-Using-an-integrated-debugger-Watching-variables.md"
          - "3-9-Using-an-integrated-debugger-The-call-stack.md"
          - "3-10-Finding-issues-before-they-become-problems.md"
          - "3-x-Chapter-3-summary-and-quiz.md"
      - 4. 基础数据类型:
          - "4-1-Introduction-to-fundamental-data-types.md"
          - "4-2-Void.md"
          - "4-3-Object-sizes-and-the-sizeof-operator.md"
          - "4-4-Signed-integers.md"
          - "4-5-Unsigned-integers-and-why-to-avoid-them.md"
          - "4-6-Fixed-width-integers-and-size_t.md"
          - "4-7-Introduction-to-scientific-notation.md"
          - "4-8-Floating-point-numbers.md"
          - "4-9-Boolean-values.md"
          - "4-10-Introduction-to-if-statements.md"
          - "4-11-Chars.md"
          - "4-12-Introduction-to-type-conversion-and-static_cast.md"
          - "4-13-Const-variables-and-symbolic-constants.md"
          - "4-14-Compile-time-constants-constant-expressions-and-constexpr.md"
          - "4-15-Literals.md"
          - "4-16-Numeral-systems-decimal-binary-hexadecimal-and-octal.md"
          - "4-17-an-introduction-to-std-string.md"
          - "4-18-Introduction-to-std-string_view.md"
          - "4-x-Chapter-4-summary-and-quiz.md"
      - 5. 运算符:
          - "5-1-Operator-precedence-and-associativity.md"
          - "5-2-Arithmetic-operators.md"
          - "5-3-Modulus-and-Exponentiation.md"
          - "5-4-Increment-decrement-operators-and-side-effects.md"
          - "5-5-Comma-and-conditional-operators.md"
          - "5-6-Relational-operators-and-floating-point-comparisons.md"
          - "5-7-Logical-operators.md"
          - "5-x-Chapter-5-summary-and-quiz.md"
      - 6. 作用域，生命周期和链接:
          - "6-1-Compound-statements-blocks.md"
          - "6-2-User-defined-namespaces-and-the-scope-resolution-operator.md"
          - "6-3-Local-variables.md"
          - "6-4-Introduction-to-global-variables.md"
          - "6-5-Variable-shadowing-name-hiding.md"
          - "6-6-Internal-linkage.md"
          - "6-7-External-linkage-and-variable-forward-declarations.md"
          - "6-8-Why-non-const-global-variables-are-evil.md"
          - "6-9-Sharing-global-constants-across-multiple-files-using-inline-variables.md"
          - "6-10-Static-local-variables.md"
          - "6-11-Scope-duration-and-linkage-summary.md"
          - "6-12-Using-declarations-and-using directives.md"
          - "6-13-Inline-functions.md"
          - "6-14-Constexpr-and-consteval-functions.md"
          - "6-15-Unnamed-and-inline-namespaces.md"
          - "6-x-Chapter-6-summary-and-quiz.md"
      - 7. 控制流和错误处理:
          - "7-1-Control-flow-introduction.md"
          - "7-2-If-statements-and-blocks.md"
          - "7-3-Common-if-statement-problems.md"
          - "7-4-Switch-statement-basics.md"
          - "7-5-Switch-fallthrough-and-scoping.md"
          - "7-6-Goto-statements.md"
          - "7-7-Intro-to-loops-and-while-statements.md"
          - "7-8-Do-while-statements.md"
          - "7-9-For-statements.md"
          - "7-10-Break-and-continue.md"
          - "7-11-Halts-exiting-your-program-early.md"
          - "7-12-Introduction-to-testing-your-code.md"
          - "7-13-Code-coverage.md"
          - "7-14-Common-semantic-errors-in-c.md"
          - "7-15-Detecting-and-handling-errors.md"
          - "7-16-std-cin-and-handling-invalid-input.md"
          - "7-17-assert-and-static-assert.md"
          - "7-18-introduction-to-random-number-generation.md"
          - "7-19-generating-random-numbers-using-mersenne-twister.md"
          - "7-x-Chapter-7-summary-and-quiz.md"
      - 8. 类型转换和函数重载:
          - "8-1-Implicit-type-conversion-coercion.md"
          - "8-2-Floating-point-and-integral-promotion.md"
          - "8-3-Numeric-conversions.md"
          - "8-4-Arithmetic-conversions.md"
          - "8-5-Explicit-type-conversion-casting-and-static-cast.md"
          - "8-6-Typedefs-and-type-aliases.md"
          - "8-7-Type-deduction-for-objects-using-the auto-keyword.md"
          - "8-8-Type-deduction-for-functions.md"
          - "8-9-Introduction-to-function-overloading.md"
          - "8-10-Function-overload-differentiation.md"
          - "8-11-Function-overload-resolution-and-ambiguous-matches.md"
          - "8-12-Default-arguments.md"
          - "8-13-Function-templates.md"
          - "8-14-Function-template-instantiation.md"
          - "8-15-Function-templates-with-multiple-template-types.md"
          - "8-x-Chapter-8-summary-and-quiz.md"
      - 9. 复合类型-引用和指针:
          - "9-1-Introduction-to-compound-data-types.md"
          - "9-2-Value-categories-lvalues-and-rvalues.md"
          - "9-3-Lvalue-references.md"
          - "9-4-Lvalue-references-to-const.md"
          - "9-5-Pass-by-lvalue-reference.md"
          - "9-6-Introduction-to-pointers.md"
          - "9-7-Null-pointers.md"
          - "9-8-Pointers-and-const.md"
          - "9-9-Pass-by-address.md"
          - "9-10-Pass-by-address-part-2.md"
          - "9-11-Return-by-reference-and-return-by-address.md"
          - "9-12-Type-deduction-with-pointers-references-and-const.md"
          - "9-x-Chapter-9-comprehensive-quiz.md"
      - 10. 复合类型-枚举和结构体:
          - "10-1-Introduction-to-program-defined-user-defined-types.md"
          - "10-2-unscoped-enumerations.md"
          - "10-3-unscoped-enumeration-input-and-output.md"
          - "10-4-scoped-enumerations-enum-classes.md"
          - "10-5-Introduction-to-structs-members-and-member-selection.md"
          - "10-6-struct-aggregate-initialization.md"
          - "10-7-default-member-initialization.md"
          - "10-8-struct-passing-and-miscellany.md"
          - "10-9-member-selection-with-pointers-and-references.md"
          - "10-10-class-templates.md"
          - "10-11-class-template-argument-deduction-and-deduction -guides.md"
          - "10-x-Chapter-10-comprehensive-quiz.md"
          - "10-y-using-a-language-reference.md"
      - 11. 数组，字符串和动态内存分配:
          - "11-1-Arrays-Part-I.md"
          - "11-2-Arrays-Part-II.md"
          - "11-3-Arrays-and-loops.md"
          - "11-4-Sorting-an-array-using-selection-sort.md"
          - "11-5-Multidimensional-Arrays.md"
          - "11-6-C-style-strings.md"
          - "11-7-std-string-view-part-2.md"
          - "11-8-Pointers-and-arrays.md"
          - "11-9-Pointer-arithmetic-and-array-indexing.md"
          - "11-10-C-style-string-symbolic-constants.md"
          - "11-11-Dynamic-memory-allocation-with-new-and-delete.md"
          - "11-12-Dynamically-allocating-arrays.md"
          - "11-13-For-each-loops.md"
          - "11-14-Void-pointers.md"
          - "11-15-Pointers-to-pointers-and-dynamic-multidimensional-arrays.md"
          - "11-16-An-introduction-to-std-array.md"
          - "11-17-An-introduction-to-std-vector.md"
          - "11-18-Introduction-to-iterators.md"
          - "11-19-Introduction-to-standard-library-algorithms.md"
          - "11-x-chapter-11-comprehensive-quiz.md"
      - 12. 函数:
          - "12-1-function-pointers.md"
          - "12-2-the-stack-and-the-heap.md"
          - "12-3-std-vector-capacity-and-stack-behavior.md"
          - "12-4-recursion.md"
          - "12-5-command-line-arguments.md"
          - "12-6-Ellipsis-and-why-to-avoid-them.md"
          - "12-7-introduction-to-lambdas-anonymous-functions.md"
          - "12-8-lambda-captures.md"
          - "12-x-Chapter-12-comprehensive-quiz.md"
      - 13. 面向对象编程基础:
          - "13-1-welcome-to-object-oriented-programming.md"
          - "13-2-classes-and-class-members.md"
          - "13-3-public-vs-private-access-specifiers.md"
          - "13-4-access-functions-and-encapsulation.md"
          - "13-5-constructors.md"
          - "13-6-constructor-member-initializer-lists.md"
          - "13-7-non-static-member-initialization.md"
          - "13-8-overlapping-and-delegating-constructors.md"
          - "13-9-destructors.md"
          - "13-10-the-hidden-this-pointer.md"
          - "13-11-class-code-and-header-files.md"
          - "13-12-const-class-objects-and-member-functions.md"
          - "13-13-static-member-variables.md"
          - "13-14-static-member-functions.md"
          - "13-15-friend-functions-and-classes.md"
          - "13-16-anonymous-objects.md"
          - "13-17-nested-types-in-classes.md"
          - "13-18-timing-your-code.md"
          - "13-x-Chapter-13-comprehensive-quiz.md"
      - 14. 操作符重载:
          - "14-1-introduction-to-operator-overloading.md"
          - "14-2-overloading-the-arithmetic-operators-using-friend-functions.md"
          - "14-3-overloading-operators-using-normal-functions.md"
          - "14-4-overloading-the-IO-operators.md"
          - "14-5-overloading-operators-using-member-functions.md"
          - "14-6-overloading-unary-operators-+--and-!.md"
          - "14-7-overloading-the-comparison-operators.md"
          - "14-8-overloading-the-increment-and-decrement-operators.md"
          - "14-9-overloading-the-subscript-operator.md"
          - "14-10-overloading-the-parenthesis-operator.md"
          - "14-11-Overloading-typecasts.md"
          - "14-12-the-copy-constructor.md"
          - "14-13-copy-initialization.md"
          - "14-14-converting-constructors-explicit-and-delete.md"
          - "14-15-overloading-the-assignment-operator.md"
          - "14-16-shallow-vs-deep-copying.md"
          - "14-17-overloading-operators-and-function-templates.md"
          - "14-x-Chapter-14-comprehensive-quiz.md"
      - 16. 对象关系简介:
          - "16-1-object-relationships.md"
          - "16-2-composition.md"
          - "16-3-aggregation.md"
          - "16-4-association.md"
          - "16-5-dependencies.md"
          - "16-6-container-classes.md"
          - "16-7-std-initializer_list.md"
          - "16-x-Chapter-16-comprehensive-quiz.md"
      - 17. 继承:
          - "17-1-introduction-to-inheritance.md"
          - "17-2-basic-inheritance-in-c++.md"
          - "17-3-order-of-construction-of-derived-classes.md"
          - "17-4-constructors-and-initialization-of-derived-classes.md"
          - "17-5-inheritance-and-access-specifiers.md"
          - "17-6-adding-new-functionality-to-a-derived-class.md"
          - "17-7-calling-inherited-functions-and-overriding-behavior.md"
          - "17-8-Hiding-inherited-functionality.md"
          - "17-9-multiple-inheritance.md"
          - "17-x-Chapter-17-comprehensive-quiz.md"
      - 18. 虚函数:
          - "18-1-pointers-and-references-to-the-base-class-of-derived-objects.md"
          - "18-2-virtual-functions-and-polymorphism.md"
          - "18-3-the-override-and-final-specifiers-and-covariant-return-types.md"
          - "18-4-virtual-destructors-virtual-assignment-and-overriding-virtualization.md"
          - "18-5-early-binding-and-late-binding.md"
          - "18-6-the-virtual-table.md"
          - "18-7-pure-virtual-functions-abstract-base-classes-and- interface-classes.md"
          - "18-8-virtual-base-classes.md"
          - "18-9-object-slicing.md"
          - "18-10-dynamic-casting.md"
          - "18-11-printing-inherited-classes-using-operator<<.md"
          - "18-x-Chapter-18-comprehensive-quiz.md"
      - 19. 模板和类:
          - "19-x-Chapter-19-comprehensive-quiz.md"
      - 20. 异常:
          - "20-x-Chapter-20-comprehensive-quiz.md"
      - M. move和智能指针:
          - "M-1-introduction-to-smart-pointers-and-move-semantics.md"
          - "M-2-R-value-references.md"
          - "M-3-move-constructors-and-move-assignment.md"
          - "M-4-std-move.md"
          - "M-5-std-move-if-noexcept.md"
          - "M-6-std-unique-ptr.md"
          - "M-7-std-shared-ptr.md"
          - "M-8-circular-dependency-issues-with-std-shared-ptr-and-std-weak-ptr.md"
          - "M-x-chapter-M-comprehensive-review.md"
      - 21. STL:
          - "21-1-the-standard-library.md"
          - "21-2-STL-containers-overview.md"
          - "21-3-STL-iterators-overview.md"
          - "21-4-STL-algorithms-overview.md"
      - 22. std字符串:
          - "22-1-std-string-and-std-wstring.md"
          - "22-2-std-string-construction-and-destruction.md"
          - "22-3-std-string-length-and-capacity.md"
          - "22-4-std-string-character-access-and-conversion-to-C-style-arrays.md"
          - "22-5-std-string-assignment-and-swapping.md"
          - "22-6-std-string-appending.md"
          - "22-7-std-string-inserting.md"
      - 23. 输入输出:
          - "23-1-Input-and-output-IO-streams.md"
          - "23-2-Input-with-istream.md"
          - "23-3-output-with-ostream-and-ios.md"
          - "23-4-stream-classes-for-strings.md"
          - "23-5-stream-states-and-input-validation.md"
          - "23-6-basic-file-IO.md"
          - "23-7-random-file-IO.md"
      - A. 其他话题:
          - "A-1-static-and-dynamic-libraries.md"
          - "A-2-using-libraries-with-visual-studio.md"
          - "A-3-using-libraries-with-Code-Blocks.md"
          - "A-4-C++FAQ.md"
      - B. C++标准更新:
          - "B-1-introduction-to-C++11.md"
          - "B-2-introduction-to-C++14.md"
          - "B-3-introduction-to-C++17.md"
          - "B-4-introduction-to-C++20.md"
      - O1. 位运算:
          - "O-1-bit-flags-and-bit-manipulation-via-std-bitset.md"
          - "O-2-bitwise-operators.md"
          - "O-3-bit-manipulation-with-bitwise-operators-and-bit-masks.md"
          - "O-4-converting-between-binary-and-decimal.md"
  - 翻译约定: 翻译约定.md
  - 索引: tags.md
  - 关于本站: index.md
  # - 面试八股: quiz.md
