site_name: LearnC++ 中文翻译站点
repo_url: https://github.com/hanxiaomax/Learncpp_CN
repo_name: hanxiaomax/Learncpp_CN
edit_uri: ""
theme:
  name: material
  custom_dir: overrides
  palette: 
    primary: teal
    accent: blue
  features:
    - navigation.instant
    - navigation.top
    - content.tooltips
    - header.autohide
    - navigation.indexes
    - navigation.tabs
    - navigation.prune
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - pymdownx.details
  - tables
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
plugins:
  - tags:
      tags_file: tags.md
  - search
  - roamlinks 
extra:
  search:
      language: 'zh'
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/hanxiaomax
nav:
  - 课程内容:
    - 1. C++ 基础:
      - "1-1-Statements-and-the-structure-of-a-program.md"
      - "1-2-comments.md"
      - "1-3-Introduction-to-objects-and-variables.md"
      - "1-4-Variable-assignment-and-initialization.md"
      - "1-5-Introduction-to-iostream-cout-cin-and-endl.md"
      - "1-6-Uninitialized-variables-and-undefined-behavior.md"
      - "1-7-Keywords-and-naming-identifiers.md"
      - "1-8-Whitespace-and-basic-formatting.md"
      - "1-9-Introduction-to-literals-and-operators.md"
      - "1-10-Introduction-to-expressions.md"
      - "1-11-Developing-your-first-program.md"
      - "1-x-Chapter-1-summary-and-quiz.md"
    - 2. C++ 基础-函数和文件: 
      - "2-1-Introduction-to-functions.md"
      - "2-2-Function-return-values-value-returning functions.md"
      - "2-3-Void-functions-non-value returning functions.md"
      - "2-4-Introduction-to-function-parameters-and-arguments.md"
      - "2-5-Introduction-to-local-scope.md"
      - "2-6-Why-functions-are-useful-and-how-to-use-them-effectively.md"
      - "2-7-Forward-declarations-and-definitions.md"
      - "2-8-Programs-with-multiple-code-files.md"
      - "2-9-Naming-collisions-and-an-introduction-to-namespaces.md"
      - "2-10-Introduction-to-the-preprocessor.md"
      - "2-11-Header-files.md"
      - "2-12-Header-guards.md"
      - "2-13-How-to-design-your-first-programs.md"
      - "2-x-Chapter-2-summary-and-quiz.md"
    - 3. 调试 C++ 程序: 
      - "3-1-Syntax-and-semantic-errors.md"
      - "3-2-The-debugging-process.md"
      - "3-3-A-strategy-for-debugging.md"
      - "3-4-Basic-debugging-tactics.md"
      - "3-5-More-debugging-tactics.md"
      - "3-6-Using-an-integrated-debugger-Stepping.md"
      - "3-7-Using-an-integrated-debugger-Running-and-breakpoints.md"
      - "3-8-Using-an-integrated-debugger-Watching-variables.md"
      - "3-9-Using-an-integrated-debugger-The-call-stack.md"
      - "3-10-Finding-issues-before-they-become-problems.md"
      - "3-x-Chapter-3-summary-and-quiz.md"
    - 4. 基础数据类型: 
      - "4-1-Introduction-to-fundamental-data-types.md"
      - "4-2-Void.md"
      - "4-3-Object-sizes-and-the-sizeof-operator.md"
      - "4-4-Signed-integers.md"
      - "4-5-Unsigned-integers-and-why-to-avoid-them.md"
      - "4-6-Fixed-width-integers-and-size_t.md"
      - "4-7-Introduction-to-scientific-notation.md"
      - "4-8-Floating-point-numbers.md"
      - "4-9-Boolean-values.md"
      - "4-10-Introduction-to-if-statements.md"
      - "4-11-Chars.md"
      - "4-12-Introduction-to-type-conversion-and-static_cast.md"
      - "4-13-An introduction-to-std-string.md"
      - "4-14-Literal-constants.md"
      - "4-15-Symbolic-constants-const-and-constexpr-variables.md"
      - "4-x-Chapter-4-summary-and-quiz.md"
    - 5. 运算符:
      - "5-1-Operator-precedence-and-associativity.md"
      - "5-2-Arithmetic-operators.md"
      - "5-3-Modulus-and-Exponentiation.md"
      - "5-4-Increment-decrement-operators-and-side-effects.md"
      - "5-5-Comma-and-conditional-operators.md"
      - "5-6-Relational-operators-and-floating-point-comparisons.md"
      - "5-7-Logical-operators.md"
      - "5-x-Chapter-5-summary-and-quiz.md"
    - 6. 作用域，生命周期和链接:
      - "6-4-Introduction-to-global-variables.md"
      - "6-9-Sharing-global-constants-across-multiple-files-using-inline-variables.md"
      - "6-12-Using-declarations-and-using directives.md"
    # - 7. 控制流和错误处理: index.md
    # - 8. 类型转换和函数重载: index.md
    # - 9. 复合类型-引用和指针: index.md
    # - 10. 复合类型-枚举和结构体: index.md
    # - 11. 数组，字符串和动态内存分配: index.md
    # - 12. 函数: index.md
    # - 13. 面向对象编程基础: index.md
    # - 14. 操作符重载: index.md
    # - 16. 对象关系简介: index.md
    # - 17. 继承: index.md
    # - 18. 虚函数: index.md
    # - 19. 模板和类: index.md
    # - 20. 异常: index.md
    # - 21. move和智能指针: index.md
    # - 22. STL: index.md
    # - 22. std字符串: index.md
    # - 23. 输入输出: index.md
    # - 24. 其他话题: index.md
    # - 25. C++标准更新: index.md
    # - O1. 位运算: index.md
  - 翻译约定: 翻译约定.md
  - 索引: tags.md
  - 关于本站: index.md
  
