site_name: LearnCpp-cn
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
markdown_extensions:
  - admonition
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - ezlinks:
      wikilinks: true