site_name: LearnCpp-cn
theme:
  name: material
  palette:
    primary: amber
  features:
    - navigation.instant
    - navigation.top
    - content.tooltips
    - header.autohide
    - navigation.indexes
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - tags
  - ezlinks:
      wikilinks: true
nav:
  - 1. C++ 基础: index.md
  - 2. C++ 基础-函数和文件: index.md
  - 3. 调试 C++ 程序: index.md
  - 4. 基础数据类型: index.md