site_name: LearnCpp 中文翻译站点
repo_url: https://github.com/hanxiaomax/Learncpp_CN
repo_name: hanxiaomax/Learncpp_CN
edit_uri: ""
theme:
  name: material
  custom_dir: overrides
  palette: 
    primary: brown
  features:
    - navigation.instant
    - navigation.top
    - content.tooltips
    - header.autohide
    - navigation.indexes
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - tags
  - search
  - roamlinks 
extra:
  search:
      language: 'zh'
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/hanxiaomax
nav:
  - 课程内容:
    - 1. C++ 基础:
      - "1-1-Statements-and-the-structure-of-a-program.md"
      - "1-2-comments.md"
      - "1-3-Introduction-to-objects-and-variables.md"
      - "1-4-Variable-assignment-and-initialization.md"
      - "1-5-Introduction-to-iostream-cout-cin-and-endl.md"
      - "1-6-Uninitialized-variables-and-undefined-behavior.md"
      - "1-7-Keywords-and-naming-identifiers.md"
      - "1-8-Whitespace-and-basic-formatting.md"
      - "1-9-Introduction-to-literals-and-operators.md"
      - "1-10-Introduction-to-expressions.md"
      - "1-11-Developing-your-first-program.md"
      - "1-x-Chapter-1-summary-and-quiz.md"
    - 2. C++ 基础-函数和文件: 
      - "2-1-Introduction-to-functions.md"
      - "2-2-Function-return-values-value-returning functions.md"
      - "2-3-Void-functions-non-value returning functions.md"
      - "2-4-Introduction-to-function-parameters-and-arguments.md"
      - "2-5-Introduction-to-local-scope.md"
      - "2-6-Why-functions-are-useful-and-how-to-use-them-effectively.md"
      - "2-7-Forward-declarations-and-definitions.md"
      - "2-8-Programs-with-multiple-code-files.md"
    - 3. 调试 C++ 程序: index.md
    - 4. 基础数据类型: index.md
    - 5. 运算符: index.md
    - 6. 作用域，生命周期和链接: index.md
    - 7. 控制流和错误处理: index.md
    - 8. 类型转换和函数重载: index.md
    - 9. 复合类型-引用和指针: index.md
    - 10. 复合类型-枚举和结构体: index.md
    - 11. 数组，字符串和动态内存分配: index.md
    - 12. 函数: index.md
    - 13. 面向对象编程基础: index.md
    - 14. 操作符重载: index.md
    - 16. 对象关系简介: index.md
    - 17. 继承: index.md
    - 18. 虚函数: index.md
    - 19. 模板和类: index.md
    - 20. 异常: index.md
    - 21. move和智能指针: index.md
    - 22. STL: index.md
    - 22. std字符串: index.md
    - 23. 输入输出: index.md
    - 24. 其他话题: index.md
    - 25. C++标准更新: index.md
    - O1. 位运算: index.md
  - 翻译约定: 翻译约定.md
  - 关于本站: about.md