site_name: LearnCpp-cn
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.tooltips
    - header.autohide
    - navigation.indexes
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - tags
  - ezlinks:
      wikilinks: true